version: 2.1
workflows:
  test-deploy:
    jobs:
      -testAutomation
jobs:
  testAutomation:
    steps:
      - checkout
      - run:
          name: Update
          command: apt-get -y update
      - run:
          name: Install Google Chrome Stable Version
          command: apt-get -y install google-chrome-stable



